openapi: 3.0.0
info:
  title: Amazonia-drones API
  version: 1.0.0
  description: Amazonia-drones API documentation.
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://teste-0sg8.onrender.com
    description: Production server
paths:
  /drones/path:
    post:
      summary: Returns the fastest path with total time.
      description: Sends the coordinates of the drone's path and object to get the fastest path and total time.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                starting_point:
                  type: string
                  pattern: '^[a-hA-H][1-8]$'
                object:
                  type: string
                  pattern: '^[a-hA-H][1-8]$'
                destination:
                  type: string
                  pattern: '^[a-hA-H][1-8]$'
            example:
              starting_point: A1
              object: B3
              destination: B1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  path:
                    type: array
                    items:
                      type: string
                    example:
                      - A1
                      - A2
                      - A3
                      - B3
                      - B2
                      - B1
                  total_time:
                    type: number
                    example: 79.14000000000001
        '400':
          description: Invalid input

  /drones/paths:
    get:
      summary: Returns the last 10 paths.
      description: Returns the last 10 fastest paths calculated.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 3
                    starting_point:
                      type: string
                      example: A1
                    object:
                      type: string
                      example: F8
                    destination:
                      type: string
                      example: E1
                    path:
                      type: string
                      example: A1 - B1 - C1 - C2 - C3 - D3 - E3 - F3 - F4 - F5 - F6 - F7 - F8 - F8 - F7 - F6 - F5 - F4 - F3 - F2 - F1 - E1
                    total_time:
                      type: number
                      example: 342.16999999999996
                    created_at:
                      type: string
                      format: date-time
                      example: '2023-05-20T16:16:26.616Z'
                    updated_at:
                      type: string
                      format: date-time
                      example: '2023-05-20T16:16:26.616Z'
                example:
                  - id: 1
                    starting_point: A1
                    object: F4
                    destination: B8
                    path: A1 - B1 - C1 - C2 - C3 - D3 - E3 - F3 - F4 - F4 - F5 - E5 - E6 - D6 - C6 - B6 - B7 - B8
                    total_time: 261.13
                    created_at: '2023-05-20T15:20:40.037Z'
                    updated_at: '2023-05-20T15:20:40.037Z'